### ISSUE TITLE
Filter life not displayed

### ISSUE THREAD

**Issue by ghost** [rgavril/homebridge-xiaomi-air-purifier3#10]
I cannot find the filter life information on the home app.

**Comment by cece-mae** [comment]
The Apple Home app doesn’t expose the filter life indication unfortunately, but 3rd party apps like [Eve Degree](https://apps.apple.com/au/app/eve-for-homekit/id917695792) do: 

![5ADB6EE4-E722-4FA9-9116-2A3E2186A54C](https://user-images.githubusercontent.com/7719805/76259573-fbb29000-62a9-11ea-84f6-ba3255195bbe.png)

**Comment by ghost** [comment]
Hmm.. i'm prettur sure the this plugin showed the filer life in the home app for my old 2s https://www.npmjs.com/package/homebridge-mi-airpurifier

**Comment by rgavril** [comment]
@malmentm : Thanks for pointing me to the right direction.

The documentation on the subject is misleading, and apparently it is possible to show filter app in Home app by attaching those properties to the _AirPurifier_ service and not have an additional _FilterMaintenance_ service.

This will pop in the next release ;)

**Comment by ndejong5** [comment]
Was this ever implemented I am not seeing it?
