### ISSUE TITLE
HAP Warning: Characteristic

### ISSUE THREAD

**Issue by Nastras** [rgavril/homebridge-xiaomi-air-purifier3#12]
Hello @rgavril 

i updated your plugin to the latest Version and now i get a HAP warning message.
After a restart of the instance the warning is still present.

I know it is nothing bad but maybe you can fix it with the next update?

Thank You!

![A63BE4F7-6095-40D5-B21A-3F1297B24FA4](https://user-images.githubusercontent.com/27686185/76442783-b97c7200-63c1-11ea-9769-5f1b4674add6.jpeg)

**Comment by rgavril** [comment]
You can safely ignore it. It refers to _Filter Life_ and _Filter Condition_ not being required or optional characteristics of an _Air Purifier_ service.

That is true according to the specs provided by apple(HAPS), that were used to implement HAP-NodeJS, but in practice this is not the case.

The documented way of attaching them to the Air Purifier (using an _Filter Maintenance_ service) will prevent them from showing up in Home app so the only way they work is as characteristic of the _Air Purifier_ service.

PS: I looked at other homebridge plugins and they either do it like this (and have warnings) or they implement the specs but the filter info doesn’t show up in Home app.
