### ISSUE TITLE
Don't find a way to keep it working ... 

### ISSUE THREAD

**Issue by dgproductions88** [rgavril/homebridge-xiaomi-air-purifier3#2]
Hi there! thanks for the plugin!

Just bought brand new 'xiaomi air purifier 2h EU model' and I'm trying to incorporate to my already installed platform 'homebridge' where i have several brand accessories working fine.

I was trying to install following your guide but i'm facing the next:
`MIoT Device (did: 133837982) is now connected`

`UnhandledPromiseRejectionWarning: MIOTDevice not responding : Error: Method not found.`

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

`[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Could you tell me what i'm doing wrong?

Here my raspberry 3b + homebridge versions:
- Node v.12.14.1
- npm 6.13.6
- homebridge v.0.4.50

Thanks and in advance!

Cheers

**Comment by rgavril** [comment]
Hi,

This plugin is specific to Air Purifier 3/3H which has a different API compared to the previous models. 

You should use a different plugin for your device, for example:
- [homebridge-mi-airpurifier](https://github.com/YinHangCode/homebridge-mi-airpurifier)
- [homebridge-mi-air-purifier](https://github.com/seikan/homebridge-mi-air-purifier)
