### ISSUE TITLE
Mode switch Manual/Automatic not visible in Home app

### ISSUE THREAD

**Issue by cece-mae** [rgavril/homebridge-xiaomi-air-purifier3#3]
Firstly, I'd like to say thank you so much for the plugin!! Really appreciate your work. 

Whilst the Eve Home app shows a switch for Manual and Automatic modes, the Apple Home app doesn't. I know it supports exposing such a switch but the plugin doesn't seem to do so. 

When I turn the purifier on, it goes to Auto. That's fine. If I turn the fan speed up, it switches to Manual. But now I want to go back to Auto. How? The only way seems to be to turn off and on again which resets back to Auto (shouldn't it save the state?)

If I use the Eve app, I have a Manual/Auto mode switch. But it is not shown in Apple Home and Siri doesn't see it. 

Is there any way to improve this functionality?

Thank you!

**Comment by rgavril** [comment]
Hi,

It’s Apple’s Home app that is messed up. By default the sensors and air purifier are grouped into a single tile. When grouped, only certain controls get exposed and that’s why automatic/manual mode is not displayed. 

You should either ungroup the devices by selecting ‘Show as Separate Tiles’ from the grouped tile settings page or accessing the _Air Purifier_ device from the  ‘Accessories’ submenu in grouped tile’s setting page.

**Comment by cece-mae** [comment]
Thank you for your reply, you are right! Ungrouped and I have the controls. Appreciate your help.
