### ISSUE TITLE
Support for user-configured breakpoints

### ISSUE THREAD

**Issue by mouth4war** [rgavril/homebridge-xiaomi-air-purifier3#4]
Thanks for the plugin. It works perfect. Just need to add support for user configured PM25 level breakpoints.

https://aqs.epa.gov/aqsweb/documents/codetables/aqi_breakpoints.html

**Comment by Tanote650** [comment]
Thanks for the suggestion to add an individual switch-on point at a high PM25 value in the user settings. This can be a good new feature for the user. In my application, the air purifier is operating in auto mode and also receives a start command from an external air sensor. This works very well for me, maybe this hint already helps you. Best wishes, Tom

**Comment by mouth4war** [comment]
This is for the cutoff "breakpoints" for air quality to be shown as excellent, good, fair, inferior in homekit. These are currently hard-coded and can be made user-configurable.

**Comment by rgavril** [comment]
I've just noticed that Home app can only define automations based on this "breakpoints" so having them is important for actually using the pm25 sensor (I don't actually use the sensor myself).

The current breakpoints are based on how the device is calculating it's levels and how they show up in the xiaomi app (PM25 : 35,75,115,150,250). I think I'll leave this values as default so it doesn't create confusion with regular users. 

I'll have a new release once is ready.

**Comment by mouth4war** [comment]
I understand the rationale, but those numbers are from Chinese government standards and are misleading. Maybe replace with American standards from OP which are closer to WHO standards. User health is important too :)
Say PM25: 6, 12, 35, 55, 150
< 6 is excellent
< 12 is good
< 35 is fair
< 55 is inferior
< 150 is poor

I personally use 7, 15, 20, 30, 40 for my automations.

**Comment by rgavril** [comment]
New release is available. It has configurable breakpoints and new defaults.

**Comment by mouth4war** [comment]
I noticed you added the aqi-heartbeat too. Is it reset every minute or only when homekit requests?
