### ISSUE TITLE
Firmware compatibility

### ISSUE THREAD

**Issue by mksmo** [rgavril/homebridge-xiaomi-air-purifier3#6]
Hello!
Does this plugin work with new firmware (2.0.8.0022). 
I’m afraid to update due to loss of compatibility.
Thanks for your answer!

**Comment by rgavril** [comment]
I don't know, my device is on 2.0.5.0009 and not showing any available updates.

I would recommend waiting until it's rolling up to more users and we'll see what changed. If it ain't broken, don't fix it.

**Comment by mksmo** [comment]
Thanks
