### ISSUE TITLE
Will this work with Air Purifier 2S?

### ISSUE THREAD

**Issue by ghost** [rgavril/homebridge-xiaomi-air-purifier3#9]

**Comment by ghost** [comment]
Would be nice to have an updated and AQI configurable plugin for the 2S :D

**Comment by ifeign** [comment]
Does it work with the 2S?

**Comment by ghost** [comment]
No

**Comment by rgavril** [comment]
The api that controls 3/3H devices is very different from the 2S and all the previous models.

If the older models will receive a firmware update and get switched to the new api (MIOT), I will probably put it the work to get them supported but until then they don't work.
